from .models import Idea, InnovationExperiment

class InnovationEngine:
    LIFECYCLE = ["RESEARCH","DISCOVER","IDENTIFY_OPPORTUNITY","GENERATE_IDEAS","COMBINE_KNOWLEDGE","EVALUATE_NOVELTY","DESIGN","PROTOTYPE","TEST","MEASURE","ITERATE","VALIDATE","REVIEW","HUMAN_APPROVAL_IF_REQUIRED","RELEASE_DEPLOY","MONITOR","LEARN"]

    def novelty(self, prior_art_found: bool, prior_art_checked: bool, similarity: bool = False) -> str:
        if not prior_art_checked: return "PRIOR_ART_UNKNOWN"
        if prior_art_found and similarity: return "SIMILAR"
        if prior_art_found: return "KNOWN"
        return "POTENTIALLY_NEW"

    def validate(self, evidence: bool, prototype: bool, testing: bool, metrics: bool, risk_review: bool) -> str:
        return "VALIDATED" if all((evidence, prototype, testing, metrics, risk_review)) else "UNVERIFIED"

    def authorize_deployment(self, risk: str, approval: str | None) -> bool:
        if risk in {"HIGH", "CRITICAL", "REGULATED"}: return approval == "APPROVED"
        return approval in {"APPROVED", "NOT_REQUIRED"}

    def invention_status(self, novelty_status: str, validated: bool) -> str:
        if novelty_status in {"KNOWN", "SIMILAR", "PRIOR_ART_UNKNOWN", "UNKNOWN"}: return "CONCEPT"
        return "VALIDATED" if validated else "EXPERIMENTAL"

    def baseline_claim(self, metric: str, baseline: float | None, candidate: float | None) -> dict:
        if baseline is None or candidate is None:
            return {"status":"UNKNOWN", "metric":metric}
        return {"status":"MEASURED", "metric":metric, "baseline":baseline, "candidate":candidate, "delta":candidate-baseline}

    def generate_variants(self, problem: str, solution: str, methods: list[str]) -> list[Idea]:
        return [Idea(f"idea-{i+1}", problem, solution, f"Generated by {method}", generation_method=method) for i, method in enumerate(methods)]
