def research_lifecycle() -> list[str]:
    return ["RESEARCH","DISCOVER","COLLECT_EVIDENCE","COMPARE_SOURCES","ANALYZE","SYNTHESIZE","DETECT_KNOWLEDGE_GAPS","GENERATE_HYPOTHESES","TEST_VALIDATE","PEER_REVIEW","HUMAN_REVIEW_IF_REQUIRED","PUBLISH_VERIFIED_KNOWLEDGE","MONITOR","LEARN"]
